// Module declarations
pub mod activation;
pub mod architecture;
pub mod attention;
pub mod batch_norm;
pub mod complexity;
pub mod convergence;
pub mod ensemble;
pub mod gradient;
pub mod learning_rate;
pub mod memory;
pub mod metrics;
pub mod quantization;
pub mod regularization;
pub mod weight;

// Re-export public analysis functions
pub use activation::analyze_activation_pattern_analysis;
pub use architecture::analyze_model_architecture_changes;
pub use attention::analyze_attention_patterns;
pub use batch_norm::analyze_batch_normalization_analysis;
pub use complexity::analyze_model_complexity_assessment;
pub use convergence::analyze_convergence_patterns;
pub use ensemble::analyze_ensemble_patterns;
pub use gradient::analyze_gradient_patterns;
pub use learning_rate::analyze_learning_rate_changes;
pub use memory::analyze_memory_usage_changes;
pub use metrics::analyze_training_metrics;
pub use quantization::analyze_quantization_patterns;
pub use regularization::analyze_regularization_impact;
pub use weight::analyze_weight_distribution_analysis;
