name: Bug Report
description: File a bug report for diffai
title: "[Bug]: "
labels: ["type: bug", "priority: medium"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        
  - type: input
    id: version
    attributes:
      label: diffai Version
      description: What version of diffai are you running?
      placeholder: e.g., v0.2.6
    validations:
      required: true
      
  - type: dropdown
    id: file-format
    attributes:
      label: File Format
      description: What file format were you comparing?
      options:
        - Safetensors (.safetensors)
        - PyTorch (.pt, .pth)
        - NumPy (.npy, .npz)
        - MATLAB (.mat)
        - JSON
        - YAML
        - Other
    validations:
      required: true
      
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
      
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Run command '...'
        2. With files '...'
        3. See error
    validations:
      required: true
      
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
