name: Feature Request
description: Suggest an idea for diffai
title: "[Feature]: "
labels: ["type: feature", "priority: low"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature for diffai!
        
  - type: dropdown
    id: area
    attributes:
      label: Feature Area
      description: Which area does this feature relate to?
      options:
        - Core comparison engine
        - ML analysis features
        - Output formats
        - CLI interface
        - File format support
        - Performance
        - Documentation
        - Other
    validations:
      required: true
      
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when...
      
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
      
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context, use cases, or screenshots about the feature request here.
