[project]
name = "diffai-real-models-test"
version = "0.1.0"
description = "Real ML models downloading for diffai testing"
dependencies = [
    "huggingface-hub>=0.20.0",
    "requests>=2.31.0",
    "urllib3>=2.0.0",
]