name: Performance Benchmark

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  schedule:
    # Run weekly on Sundays at 2 AM UTC
    - cron: '0 2 * * 0'

jobs:
  benchmark:
    uses: kako-jun/.github/.github/workflows/rust-cli-kiln-benchmark.yml@main
    with:
      project-name: ${{ github.event.repository.name }}
    secrets: inherit