name: Release Act 2 - Language Wrappers

on:
  workflow_run:
    workflows: ["Release Act 1 - Core"]
    types:
      - completed
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag to publish wrappers for'
        required: true
        type: string

permissions:
  contents: write

jobs:
  release-act2:
    uses: kako-jun/.github/.github/workflows/rust-cli-kiln-release-act2.yml@main
    with:
      project-name: ${{ github.event.repository.name }}
    secrets: inherit