name: Release Act 1 - Core

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag'
        required: true
        type: string

permissions:
  contents: write

jobs:
  release-act1:
    uses: kako-jun/.github/.github/workflows/rust-cli-kiln-release-act1.yml@main
    with:
      project-name: ${{ github.event.repository.name }}
    secrets: inherit