name: Release Act 2 - Language Wrappers

on:
  workflow_run:
    workflows: ["Release Act 1 - Core"]
    types:
      - completed
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag to publish wrappers for'
        required: true
        type: string

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  get-tag:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    outputs:
      tag-name: ${{ steps.get-tag.outputs.tag }}
    steps:
    - name: Get tag name from workflow run
      id: get-tag
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          TAG_NAME="${{ github.event.inputs.tag }}"
        else
          # Get tag from the triggering workflow run context
          WORKFLOW_RUN_ID="${{ github.event.workflow_run.id }}"
          TAG_NAME=$(gh api repos/${{ github.repository }}/actions/runs/$WORKFLOW_RUN_ID --jq '.head_branch // .head_sha' | sed 's/refs\/tags\///')
          
          # Fallback: get latest release including drafts
          if [[ ! "$TAG_NAME" =~ ^v[0-9] ]]; then
            TAG_NAME=$(gh api repos/${{ github.repository }}/releases --jq '.[0].tag_name')
          fi
        fi
        echo "tag=$TAG_NAME" >> $GITHUB_OUTPUT
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-npm:
    needs: get-tag
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        registry-url: 'https://registry.npmjs.org'
    
    - name: Download all platform binaries for npm package
      working-directory: diffai-npm
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        TAG_NAME="${{ needs.get-tag.outputs.tag-name }}"
        node scripts/download-all-binaries.js
    
    - name: Publish to npm
      working-directory: diffai-npm
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: npm publish

  publish-pypi:
    needs: get-tag
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: windows-latest
            target: x86_64-pc-windows-msvc
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}
    
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
    
    - name: Install maturin
      run: pip install maturin
    
    - name: Build and publish wheel
      working-directory: diffai-python
      env:
        MATURIN_PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
      run: |
        maturin build --release --target ${{ matrix.target }} --out dist --find-interpreter
        maturin publish --skip-existing